version: "3.8"
services:
  frontend:
    build:
      context: "./frontend"
      dockerfile: "dev.Dockerfile"
    restart: "unless-stopped"
    environment:
      - "HOST=$FRONTEND_HOST"
      - "PORT=$FRONTEND_PORT"
      - "NUXT_PUBLIC_BASE_URL=$BASE_URL"
    ports:
      - "$FRONTEND_PORT:$FRONTEND_PORT"
    volumes:
      - "./frontend:/srv/app"
    networks:
      - flowchart

  backend:
    build:
      context: "./backend"
      dockerfile: "dev.Dockerfile"
    restart: "unless-stopped"
    environment:
      - "DEBUG=$DEBUG"
      - "HOST=$BACKEND_HOST"
      - "PORT=$BACKEND_PORT"
      - "DF_KIND=$DF_KIND"
      - "DF_CONNECTION_PATH=$DF_CONNECTION_PATH"
    ports:
      - "$BACKEND_PORT:$BACKEND_PORT"
    volumes:
      - "./backend:/srv/app"
    networks:
      - flowchart

networks:
  flowchart:
